name = "Pitches"
uuid = "71ce3a53-bc01-4ee9-b4af-5ce581ee5149"
authors = ["Christoph Finkensiep <chfin@chfin.de>"]
version = "0.1.1"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
