# This is a basic workflow to help you get started with Actions

name: Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1.0', '1', 'nightly']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # setup the julia environment
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      # build the package
      - uses: julia-actions/julia-buildpkg@latest
      # run tests (also generates coverage
      - uses: julia-actions/julia-runtest@latest
      # upload coverage reports to codecov
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
